/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_httprpc_helios_WindowsAudioPlayer */

#ifndef _Included_org_httprpc_helios_WindowsAudioPlayer
#define _Included_org_httprpc_helios_WindowsAudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_httprpc_helios_WindowsAudioPlayer
 * Method:    construct
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_httprpc_helios_WindowsAudioPlayer_construct
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_httprpc_helios_WindowsAudioPlayer
 * Method:    play
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_httprpc_helios_WindowsAudioPlayer_play
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_httprpc_helios_WindowsAudioPlayer
 * Method:    pause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_httprpc_helios_WindowsAudioPlayer_pause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_httprpc_helios_WindowsAudioPlayer
 * Method:    isPlaying
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_httprpc_helios_WindowsAudioPlayer_isPlaying
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_httprpc_helios_WindowsAudioPlayer
 * Method:    getPosition
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_httprpc_helios_WindowsAudioPlayer_getPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_httprpc_helios_WindowsAudioPlayer
 * Method:    setPosition
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_org_httprpc_helios_WindowsAudioPlayer_setPosition
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_httprpc_helios_WindowsAudioPlayer
 * Method:    getVolume
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_httprpc_helios_WindowsAudioPlayer_getVolume
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_httprpc_helios_WindowsAudioPlayer
 * Method:    setVolume
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_httprpc_helios_WindowsAudioPlayer_setVolume
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_httprpc_helios_WindowsAudioPlayer
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_httprpc_helios_WindowsAudioPlayer_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
