plugins {
    id 'application'
}

repositories {
    mavenCentral()
    mavenLocal()
}

def osName = System.getProperty("os.name").toLowerCase()
def osArch = System.getProperty("os.arch").toLowerCase()

def javaFXClassifier
if (osName.startsWith("mac")) {
    if (osArch == "aarch64") {
        javaFXClassifier = "mac-aarch64"
    } else {
        javaFXClassifier = "mac"
    }
} else if (osName.startsWith("lin")) {
    if (osArch == "aarch64") {
        javaFXClassifer = "linux-aarch64"
    } else {
        javaFXClassifer = "linux"
    }
} else if (osName.startsWith("win")) {
    javaFXClassifier = "win"
} else {
    javaFXClassifier = ""
}

dependencies {
    implementation "org.httprpc:kilo-client:${kiloVersion}"
    implementation "org.httprpc:sierra:${sierraVersion}"
    implementation "com.formdev:flatlaf:${flatLafVersion}"
    implementation "com.formdev:flatlaf-extras:${flatLafVersion}"
    implementation "org.xerial:sqlite-jdbc:${sqliteJDBCVersion}"
    implementation "net.jthink:jaudiotagger:${jAudioTaggerVersion}"
    implementation "net.java.dev.jna:jna-platform:${jnaVersion}"

    if (osName.startsWith("mac")) {
        compileOnly "org.openjfx:javafx-base:${javaFXVersion}:${javaFXClassifier}"
        compileOnly "org.openjfx:javafx-graphics:${javaFXVersion}:${javaFXClassifier}"
        compileOnly "org.openjfx:javafx-media:${javaFXVersion}:${javaFXClassifier}"
    } else {
        implementation "org.openjfx:javafx-base:${javaFXVersion}:${javaFXClassifier}"
        implementation "org.openjfx:javafx-graphics:${javaFXVersion}:${javaFXClassifier}"
        implementation "org.openjfx:javafx-media:${javaFXVersion}:${javaFXClassifier}"
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs = [
        '-parameters'
    ]
}

version = '1.0.0'

application {
    applicationName = 'Helios'

    mainClass = 'org.httprpc.helios.MainFrame'
}

jar {
    dependsOn configurations.runtimeClasspath

    archiveFileName = "${project.name}.jar"

    manifest {
        attributes (
            'Implementation-Title': application.applicationName,
            'Implementation-Version': project.version,
            'Main-Class': application.mainClass
        )
    }

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.register("packageMacOS", Exec) {
    dependsOn 'jar'

    workingDir = projectDir

    executable = 'bin/package-macos.sh'
    args = ["${project.name}", "${application.applicationName}", "${version}"]
}

tasks.register("packageWindows", Exec) {
    dependsOn 'jar'

    executable = 'jpackage'
    args = [
        '--name', "${application.applicationName}",
        '--input', 'build/libs',
        '--main-jar', "${project.name}.jar",
        '--java-options', '--enable-native-access=ALL-UNNAMED',
        '--app-version', "${version}",
        '--win-shortcut'
    ]
}
