plugins {
    id 'application'
    id 'org.gradlex.extra-java-module-info' version '1.14.2'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation "org.httprpc:sierra:${sierraVersion}"
    implementation "com.formdev:flatlaf:${flatLafVersion}"
    implementation "org.xerial:sqlite-jdbc:${sqliteJDBCVersion}"
    implementation "net.jthink:jaudiotagger:${jAudioTaggerVersion}"
}

extraJavaModuleInfo {
    module('net.jthink:jaudiotagger', 'org.jaudiotagger') {
        requires 'java.desktop'
        requires 'java.datatransfer'
        requires 'java.logging'

        exports 'org.jaudiotagger.audio'
        exports 'org.jaudiotagger.audio.exceptions'
        exports 'org.jaudiotagger.tag'
        exports 'org.jaudiotagger.tag.images'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs = [
        '-parameters',
        '-h', "${projectDir}/src/main/jni/include"
    ]
}

application {
    applicationName = 'Helios'

    mainModule = 'org.httprpc.helios'
    mainClass = 'org.httprpc.helios.Helios'
}

version = '1.0.3'

tasks.register("buildMacOS", Exec) {
    executable = 'bin/build-macos.sh'
}

tasks.register("packageMacOS", Exec) {
    executable = 'jpackage'

    args = [
        '--name', "${application.applicationName}",
        '--vendor', 'httprpc.org',
        '--module', "${application.mainModule.get()}/${application.mainClass.get()}",
        '--module-path', "${configurations.runtimeClasspath.asPath}:build/libs",
        '--java-options', '--enable-native-access=org.httprpc.helios,com.formdev.flatlaf,org.xerial.sqlitejdbc',
        '--app-version', "${version}",
        '--mac-sign',
        '--mac-signing-key-user-name', System.getenv('MAC_SIGNING_KEY_USER_NAME')
    ]
}

tasks.register("notarizeMacOS", Exec) {
    dependsOn 'packageMacOS'

    executable = 'xcrun'

    args = [
        'notarytool', 'submit',
        '--apple-id', System.getenv('NOTARY_TOOL_APPLE_ID'),
        '--team-id', System.getenv('NOTARY_TOOL_TEAM_ID'),
        '--password', System.getenv('NOTARY_TOOL_PASSWORD'),
        '--wait', "${application.applicationName}-${version}.dmg"
    ]
}

tasks.register("stapleMacOS", Exec) {
    dependsOn 'notarizeMacOS'

    executable = 'stapler'

    args = ['staple', "${application.applicationName}-${version}.dmg"]
}

tasks.register("buildWindows", Exec) {
    executable = 'bin/build-windows.bat'
}

tasks.register("packageWindows", Exec) {
    executable = 'jpackage'

    args = [
        '--name', "${application.applicationName}",
        '--vendor', 'httprpc.org',
        '--module', "${application.mainModule.get()}/${application.mainClass.get()}",
        '--module-path', "${configurations.runtimeClasspath.asPath};build/libs",
        '--java-options', '--enable-native-access=org.httprpc.helios,com.formdev.flatlaf,org.xerial.sqlitejdbc',
        '--app-version', "${version}",
        '--win-shortcut'
    ]
}
