playAlbum = Play Album

editAlbum = Edit Album
deleteAlbum = Delete Album

editArtwork = Edit Artwork
deleteArtwork = Delete Artwork

imageFileFilterDescription = Image Files

confirmDeleteAlbumMessageFormat = Are you sure you want to delete %s?
confirmDeleteArtworkMessage = Are you sure you want to delete the artwork for this album?
