playAlbum = Play Album

editArtwork = Edit Artwork
deleteArtwork = Delete Artwork

imageFileFilterDescription = Image Files

confirmDeleteArtwork = Are you sure you want to delete the artwork for this album?
