windowTitle = Edit Song

artist = Artist
album = Album
title = Title

genre = Genre
year = Year

track = Track
disc = Disc
of = of

soundtrack = Soundtrack
compilation = Compilation
classical = Classical

composer = Composer

cancel = Cancel
ok = OK

timeFormat = %d:%02d

error = Error
requiredFieldFormat = %s is required.
