windowTitle = Edit Song

artist = Artist
album = Album
title = Title

genre = Genre
year = Year

trackNumber = Track Number
discNumber = Disc Number

compilation = Compilation

cancel = Cancel
ok = OK

timeFormat = %d:%02d

error = Error
requiredFieldFormat = %s is required.
