play = Play

addToPlaylist = Add to Playlist

edit = Edit
delete = Delete

album = Album
artwork = Artwork
song = Song

deleteAlbum = Delete Album
deleteSong = Delete Song

confirmDeleteMessageFormat = Are you sure you want to delete "%s"?
confirmDeleteArtworkMessageFormat = Are you sure you want to delete the artwork for %s?

compilation = Compilation
