play = Play

addToPlaylist = Add to Playlist

edit = Edit
delete = Delete
album = Album
artwork = Artwork
song = Song

title = Title
artist = Artist

deleteAlbum = Delete Album
deleteSong = Delete Song

confirmDeleteMessageFormat = Are you sure you want to delete "%s"?
confirmDeleteArtworkMessageFormat = Are you sure you want to delete the artwork for %s?
