play = Play

addToPlaylist = Add to Playlist

edit = Edit
delete = Delete

deleteAlbum = Delete Album
deleteSong = Delete Song

confirmDeleteMessageFormat = Are you sure you want to delete "%s"?
confirmDeleteArtworkMessageFormat = Are you sure you want to delete the artwork for %s?

timeFormat = %d:%02d
compilation = Compilation
