title = Helios

play = Play
pause = Pause
previous = Previous
next = Next

shuffle = Shuffle
repeat = Repeat

showQueue = Show Queue

add = Add
songs = Songs
playlist = Playlist

countFormat = %s, %s

singleArtistFormat = %d artist
multipleArtistFormat = %d artists
singleAlbumFormat = %d album
multipleAlbumFormat = %d albums
singleSongFormat = %d song
multipleSongFormat = %d songs
