title = Helios

play = Play
pause = Pause
previous = Previous
next = Next

shuffle = Shuffle
repeat = Repeat

queue = Queue

add = Add
songs = Songs
playlist = Playlist

getAlbumArtwork = Get Album Artwork

search = Search
settings = Settings

artists = Artists
genres = Genres
playlists = Playlists

countFormat = %s, %s

singleArtistFormat = %,d artist
multipleArtistFormat = %,d artists
singleAlbumFormat = %,d album
multipleAlbumFormat = %,d albums
singleSongFormat = %,d song
multipleSongFormat = %,d songs

artistAlbumFormat = %s / %s
timeFormat = %d:%02d/%d:%02d

newPlaylistName = New Playlist

audioFileFilterDescription = Audio Files
