title = Helios

play = Play
pause = Pause
previous = Previous
next = Next

shuffle = Shuffle
repeat = Repeat

queue = Queue

add = Add
songs = Songs
playlist = Playlist

search = Search
settings = Settings

artists = Artists
playlists = Playlists

countFormat = %s, %s

singleArtistFormat = %d artist
multipleArtistFormat = %d artists
singleAlbumFormat = %d album
multipleAlbumFormat = %d albums
singleSongFormat = %d song
multipleSongFormat = %d songs

songTitleFormat = %s - %s / %s

newPlaylistName = New Playlist

audioFileFilterDescription = Audio Files

addSongs = Add Songs
confirmAddSongsFormat = Do you want to add %,d songs to your music library?
