playAll = Play All

removeFromPlaylist = Remove from Playlist
editName = Edit Name
deletePlaylist = Delete Playlist

title = Title
artist = Artist
album = Album

confirmRemoveSongsMessage = Are you sure you want to remove the selected songs from this playlist?
confirmDeleteMessage = Are you sure you want to delete the selected playlist?
