/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_httprpc_helios_MacOSAudioPlayer */

#ifndef _Included_org_httprpc_helios_MacOSAudioPlayer
#define _Included_org_httprpc_helios_MacOSAudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_httprpc_helios_MacOSAudioPlayer
 * Method:    allocate
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_httprpc_helios_MacOSAudioPlayer_allocate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_httprpc_helios_MacOSAudioPlayer
 * Method:    play
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_httprpc_helios_MacOSAudioPlayer_play
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_httprpc_helios_MacOSAudioPlayer
 * Method:    pause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_httprpc_helios_MacOSAudioPlayer_pause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_httprpc_helios_MacOSAudioPlayer
 * Method:    isPlaying
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_httprpc_helios_MacOSAudioPlayer_isPlaying
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_httprpc_helios_MacOSAudioPlayer
 * Method:    getPosition
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_httprpc_helios_MacOSAudioPlayer_getPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_httprpc_helios_MacOSAudioPlayer
 * Method:    setPosition
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_httprpc_helios_MacOSAudioPlayer_setPosition
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_httprpc_helios_MacOSAudioPlayer
 * Method:    getVolume
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_httprpc_helios_MacOSAudioPlayer_getVolume
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_httprpc_helios_MacOSAudioPlayer
 * Method:    setVolume
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_httprpc_helios_MacOSAudioPlayer_setVolume
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_httprpc_helios_MacOSAudioPlayer
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_httprpc_helios_MacOSAudioPlayer_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_httprpc_helios_MacOSAudioPlayer
 * Method:    isDarkMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_httprpc_helios_MacOSAudioPlayer_isDarkMode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
