playAlbum = Play Album

editAlbum = Edit Album
deleteAlbum = Delete Album

editArtwork = Edit Artwork
deleteArtwork = Delete Artwork

imageFileFilterDescription = Image Files

confirmDeleteMessageFormat = Are you sure you want to delete "%s"?
confirmDeleteArtworkMessageFormat = Are you sure you want to delete the artwork for "%s"?
