playSelected = Play Selected

addToPlaylist = Add to Playlist
editSelected = Edit Selected
deleteSelected = Delete Selected

album = Album
artwork = Artwork

deleteAlbum = Delete Album
deleteArtwork = Delete Artwork
deleteSong = Delete Song

imageFileFilterDescription = Image Files

confirmDeleteMessageFormat = Are you sure you want to delete "%s"?
confirmDeleteArtworkMessageFormat = Are you sure you want to delete the artwork for %s?

timeFormat = %d:%02d
compilation = Compilation
