playSelection = Play Selection

addToPlaylist = Add to Playlist
editSelection = Edit Selection
deleteSelection = Delete Selection

album = Album
artwork = Artwork

deleteAlbum = Delete Album
deleteArtwork = Delete Artwork
deleteSong = Delete Song

imageFileFilterDescription = Image Files

confirmDeleteMessageFormat = Are you sure you want to delete "%s"?
confirmDeleteArtworkMessageFormat = Are you sure you want to delete the artwork for %s?

timeFormat = %d:%02d
compilation = Compilation
