plugins {
    id 'application'
}

dependencies {
    implementation "org.httprpc:kilo-client:${kiloVersion}"
    implementation "org.httprpc:sierra:${sierraVersion}"
    implementation "com.formdev:flatlaf:${flatLafVersion}"
    implementation "com.formdev:flatlaf-extras:${flatLafVersion}"
    implementation "org.xerial:sqlite-jdbc:${sqliteJDBCVersion}"
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs = [
        '-parameters'
    ]
}

jar {
    archiveFileName = "${project.name}.jar"
}
