plugins {
    id 'application'
}

dependencies {
    implementation "org.httprpc:kilo-client:${kiloVersion}"
    implementation "org.httprpc:sierra:${sierraVersion}"
    implementation "com.formdev:flatlaf:${flatLafVersion}"
    implementation "com.formdev:flatlaf-extras:${flatLafVersion}"
    implementation "org.xerial:sqlite-jdbc:${sqliteJDBCVersion}"
    implementation "net.jthink:jaudiotagger:${jAudioTaggerVersion}"
    implementation "net.java.dev.jna:jna-platform:${jnaVersion}"
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs = [
        '-parameters'
    ]
}

application {
    applicationName = 'Helios'

    mainClass = 'org.httprpc.helios.MainFrame'
}

def macSigningKeyUserName = project.findProperty('jpackage.macSigningKeyUserName') ?: ''
def teamID = project.findProperty('notarytool.teamID') ?: ''

jar {
    inputs.files(configurations.runtimeClasspath)

    doFirst {
        inputs.files.forEach {
            def name = it.name

            if (name.endsWith(".dylib") || name.endsWith(".jnilib")) {
                println "Signing ${it.absolutePath}"

                def process = Runtime.getRuntime().exec(new String[] {
                    'codesign',
                    '-vvv',
                    '--force',
                    '--verbose',
                    '--options', 'runtime',
                    '--timestamp',
                    '-s', String.format("Developer ID Application: %s (%s)", macSigningKeyUserName, teamID),
                    it.absolutePath
                })

                try (def inputStream = process.errorStream) {
                    def inputStreamReader = new BufferedReader(new InputStreamReader(inputStream))

                    String line
                    while ((line = inputStreamReader.readLine()) != null) {
                        println line
                    }
                }
            }
        }
    }

    dependsOn configurations.runtimeClasspath

    archiveFileName = "${project.name}.jar"

    manifest {
        attributes (
            'Implementation-Title': application.applicationName,
            'Implementation-Version': project.version,
            'Main-Class': application.mainClass
        )
    }

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

final macOSInstaller = "${application.applicationName}-${version}.dmg"

tasks.register('packageMacOS', Exec) {
    dependsOn 'jar'

    executable = 'jpackage'
    args = [
        '--name', application.applicationName,
        '--input', 'build/libs',
        '--main-jar', "${project.name}.jar",
        '--app-version', "${version}",
        '--icon', 'Helios.icns',
        '--mac-sign',
        '--mac-signing-key-user-name', macSigningKeyUserName
    ]
}

tasks.register("notarizeMacOS", Exec) {
    dependsOn 'packageMacOS'

    executable = 'xcrun'
    args = [
        'notarytool', 'submit',
        '--apple-id', project.findProperty('notarytool.appleID') ?: '',
        '--team-id', project.findProperty('notarytool.teamID') ?: '',
        '--password', project.findProperty('notarytool.password') ?: '',
        '--wait',
        macOSInstaller
    ]
}

tasks.register("stapleMacOS", Exec) {
    dependsOn 'notarizeMacOS'

    executable = 'xcrun'
    args = [
        'stapler', 'staple', macOSInstaller
    ]
}

tasks.register("logMacOS", Exec) {
    executable = 'xcrun'
    args = [
        'notarytool', 'log',
        '--apple-id', project.findProperty('notarytool.appleID') ?: '',
        '--team-id', project.findProperty('notarytool.teamID') ?: '',
        '--password', project.findProperty('notarytool.password') ?: '',
        project.findProperty('submissionID') ?: ''
    ]
}
